### ISSUE TITLE
Portainer fails to create admin user :-(

### ISSUE THREAD

**Issue by mmoser18** [Winbee/SynoCI#2]
I followed the instructions up the point where it reads

> On your local machine try to connect to the Portainer on this adress: http://<IP_OF_YOUR_NAS>:18050

The portainer webpage comes up and asks me to enter name and credentials for the admin user but no matter what I enter here - it always fails popping up a red alertbox stating:
`Failure: Unable to create administrator user.`

The logs read:
```
...
ash-4.3# docker-compose up -d
Creating network "ci_facto" with driver "bridge"
Creating volume "ci_nexus-data" with default driver
Creating volume "ci_portainer-data" with default driver
Creating volume "ci_jenkins-data" with default driver
Creating volume "ci_gogs-data" with default driver
Pulling nexus (sonatype/nexus3:3.3.0)...
3.3.0: Pulling from sonatype/nexus3
... <all the pull msgs. removed for brevity>
Digest: sha256:715e8079684a56f60720301504d956af081c417942172c103304eb12afaa57ac
Status: Downloaded newer image for sonatype/nexus3:3.3.0
Pulling jenkins (jenkinsci/jenkins:lts)...
lts: Pulling from jenkinsci/jenkins
... <all the pull msgs. removed for brevity>
Digest: sha256:a1c7f439da639c75135a667cf0bf164b0db546e8b790c2fce5aed77aba7bc0f1
Status: Downloaded newer image for jenkinsci/jenkins:lts
Pulling gogs (gogs/gogs:latest)...
latest: Pulling from gogs/gogs
... <all the pull msgs. removed for brevity>
Digest: sha256:d3f97051eda53aae7604a8237b1546f48020189be981d4cd50466326ee060deb
Status: Downloaded newer image for gogs/gogs:latest
Pulling portainer (portainer/portainer:latest)...
latest: Pulling from portainer/portainer
... <all the pull msgs. removed for brevity>
Digest: sha256:d6cc2c20c0af38d8d557ab994c419c799a10fe825e4aa57fea2e2e507a13747d
Status: Downloaded newer image for portainer/portainer:latest
Creating ci_nexus_1 ...
Creating ci_gogs_1 ...
Creating ci_jenkins_1 ...
Creating ci_portainer_1 ...
Creating ci_jenkins_1
Creating ci_nexus_1
Creating ci_portainer_1
Creating ci_jenkins_1 ... done
ash-4.3# docker-compose logs -f
Attaching to ci_nexus_1, ci_jenkins_1, ci_portainer_1, ci_gogs_1
nexus_1      | WARNING: no logs are available with the 'db' log driver
jenkins_1    | WARNING: no logs are available with the 'db' log driver
portainer_1  | WARNING: no logs are available with the 'db' log driver
gogs_1       | WARNING: no logs are available with the 'db' log driver
ci_portainer_1 exited with code 1

```

Any idea, what could be the reason for this?

**Comment by Winbee** [comment]
Hello,
Based on the log you provided, it seems the portainer container crash: `ci_portainer_1 exited with code 1`
The log from the container itself could give you more clue about it. How to find this log?
- Open your DSM webpage
- Open the docker app
- Go into container tab
<img width="1073" alt="Screenshot 2019-04-04 at 22 47 04" src="https://user-images.githubusercontent.com/7758451/55587655-19878480-572c-11e9-9f15-97eaa64a71c7.png">

- Double click on ci_portainer_1
- Click on the log tab => You should see more details about the error

It's been a long time I didn't run the project so there might be outdated stuff.
I tried to re-install it this evening and also got a crash of the ci_portainer. What did solve it for me was to delete the ci_portainer-data volume and rerun. Hope it can help. Cheers.

**Comment by mmoser18** [comment]
Hi - thanks for the response - appreciate it. 
However, I tried what you described and first deleted that directory (actually moved it elsewhere) but then the start of portainer kept failing completely:

```
ash-4.3# docker-compose up -d
ci_nexus_1 is up-to-date
ci_gogs_1 is up-to-date
ci_jenkins_1 is up-to-date
Starting ci_portainer_1 ...
Starting ci_portainer_1 ... error

ERROR: for ci_portainer_1  Cannot start service portainer: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:362: container init caused \"rootfs_linux.go:54: mounting \\\"/volume1/@docker/volumes/ci_portainer-data/_data\\\" to rootfs \\\"/volume1/@docker/aufs/mnt/7c0b7427a26007cd0816c47c60afe9d37d4f672bcb08b1b81cff1d13bc74ec37\\\" at \\\"/data\\\" caused \\\"stat /volume1/@docker/volumes/ci_portainer-data/_data: no such file or directory\\\"\""

ERROR: for portainer  Cannot start service portainer: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:362: container init caused \"rootfs_linux.go:54: mounting \\\"/volume1/@docker/volumes/ci_portainer-data/_data\\\" to rootfs \\\"/volume1/@docker/aufs/mnt/7c0b7427a26007cd0816c47c60afe9d37d4f672bcb08b1b81cff1d13bc74ec37\\\" at \\\"/data\\\" caused \\\"stat /volume1/@docker/volumes/ci_portainer-data/_data: no such file or directory\\\"\""
ERROR: Encountered errors while bringing up the project.
```
So - I moved that directory back.

I then found a work-around by once starting the portainer container using this commandline:

`docker run --name portainer --env ADMIN_USERNAME=admin --env ADMIN_PASS=<USER_PASSWORD_GOES_HERE> -d -p 18050:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer`

I found that solution in this thread: "https://github.com/portainer/portainer/issues/1352" (append by  jr-araujo from Jul 25, 2018 - almost at the end of the thread).
In that thread someone reported the same issue (which in his case seems to be caused by some faulty reverse proxy settings. I doubt that the reason here is the same, since I don't use any reverse proxy, yet, unless one considers docker's external-to-internal-port-mapping-and-forwarding as a reverse proxy, which of course it is - to some extent...).

Using the above apparently defined that admin user and afterwards I was able to login using the credentials provided and can run docker-compose up/down as expected.

Hope the above might help anyone who tries to follow these instructions later. 
Cheers, Michael

**Comment by Winbee** [comment]
Nice, thanks for providing your solution.
